/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "led_blue_aliases.h"
#include "led_blue.h"
#include "UART.h"
#include "PWM.h"
#include "MOTOR_aliases.h"
#include "MOTOR.h"
#include "SENSOR_aliases.h"
#include "SENSOR.h"
#include "Clock.h"
#include "ADC.h"
#include "Opamp.h"
#include "IN3_aliases.h"
#include "IN3.h"
#include "IN4_aliases.h"
#include "IN4.h"
#include "DIRECCION_aliases.h"
#include "DIRECCION.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "UART_IntClock.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

